name: Daily Dependency Scan

on:
  schedule:
    - cron: '0 0 * * *'   # Daily at midnight UTC
  workflow_dispatch:       # Manual trigger for testing

jobs:
  dependency-scan:
    permissions: write-all
    name: Run OSV Dependency Scan
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/google/osv-scanner:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@main
        with:
          scan-args: >
            --lockfile=package-lock.json
            --format=sarif
            --output=osv-results.sarif

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif
